# Generated by Django 5.1.4 on 2025-01-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('technology', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('hostlink', models.URLField()),
                ('github_link', models.URLField()),
            ],
        ),
    ]
