# Generated by Django 5.1.4 on 2025-01-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='image',
        ),
    ]
