# Generated by Django 5.1.4 on 2025-01-17 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_skills', to='user_entry.databases'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='framework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_skills', to='user_entry.frameworks'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prog_language_skills', to='user_entry.proglanguage'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='other_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_language_skills', to='user_entry.otherlanguage'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_skills', to='user_entry.tools'),
        ),
    ]
